engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: my_rubocop.yml
ratings:
  paths:
  - "darcyWeb/**.js"
  - "darcyWeb/**.rb"
exclude_paths:
  - darcyWeb/db/
  - darcyWeb/spec/
  - darcyWeb/test/
  - darcyWeb/vendor/
