version: '3'

services:
  db:
    image: postgres
  webpacker:
    build: .
    command: bash -c "bundle check || bundle install && bundle exec bin/webpack-dev-server"
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/campusmap
    ports:
      - "3035:3035"

  web:
    build: .
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/campusmap
    ports:
      - "3000:3000"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db
      - webpacker
